---

- name: Adding APT key
  apt_key:
    id: EA312927
    keyserver: keyserver.ubuntu.com

- name: Add APT repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main"
    update_cache: yes

- name: Installing package
  apt:
    pkg: "{{ mongodb_package }}"
    state: present
